version: '3.9'

services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - 443:443
    init: true
    restart: on-failure

  mariadb:
    container_name:  mariadb
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    build:
      context: ./requirements/mariadb
      args:
        - DB_DATABASE
        - DB_USER
        - DB_USER_PSW
        - DB_ROOT_PSW
    env_file:
      - .env
    init: true
    restart: on-failure
    
  
  wordpress:
    container_name: wordpress
    image: wordpress
    volumes:
      - wordpress:/var/www/html/wordpress
      - mariadb:/var/lib/mysql
    networks:
      - inception
    build: 
      context: ./requirements/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    init: true
    restart: on-failure
  
networks:
  inception:
    driver: bridge
    name: inception
  
volumes:
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: /home/lorampon/data/wordpress
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      type: none
      o: bind
      device: /home/lorampon/data/mariadb
      


    
    
    

    
